### ISSUE TITLE
Action is ignoring non-stale tag on issues.

### ISSUE THREAD

**Issue by NotLazy** [actions/stale#1178] opened 2024-09-12 17:42 UTC
**Description:** I've configured the stale action to not mark issues with the `!stale` label as stale, using `exempt-issue-labels: \!stale` which was working for some time when I added it 7 months ago, but for the last 3-4 months it's been ignoring the label

**Action version:** v5

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows
The runner is configured to use ubuntu-latest

**Runner type:**
- [x] Hosted
- [ ] Self-hosted
Github runs the action automatically.

**Repro steps:**  https://github.com/hainguyents13/mechvibes/blob/master/.github/workflows/stale.yml

**Expected behavior:** I expect the issues to not be marked as stale, as was previously working 6-7 months ago.

**Actual behavior:** Issues which should not be marked stale are being marked stale.

**Comment by priyagupta108** [comment] 2024-09-20 05:19
Hello @NotLazy 👋,
Thank you for reporting this issue. We will investigate it and get back to you as soon as we have some feedback.

**Comment by galabra** [comment] 2024-09-25 09:49
I looked for [changes](https://github.com/actions/stale/commits/3f3b0175e8c66fb49b9a6d5a0cd1f8436d4c3ab6/src/classes/issues-processor.ts) in the file that uses `exemptIssueLabels`, however didn't find anything relevant for the time span you've described.
I also tried modifying [the `exempt issue labels will not be marked stale` test](https://github.com/actions/stale/blob/3f3b0175e8c66fb49b9a6d5a0cd1f8436d4c3ab6/__tests__/main.spec.ts#L1021) in `main.spec.ts` with a `!stale` label and couldn't reproduce this behavior.

Maybe it has something to do with the escaping of the exclamation mark?

**Comment by NotLazy** [comment] 2024-11-11 19:07
> Maybe it has something to do with the escaping of the exclamation mark?

Tried without escaping and I'm getting errors now.

**Comment by suyashgaonkar** [comment] 2024-12-09 11:51
"Hi @NotLazy , We tried investigating issue with the provided details and tried the given workflow. We see that the workflow run fails with Invalid workflow file error with exempt-issue-labels: !stale . Please check the workflow run :- https://github.com/setup-actions-demo/stale-test/actions/runs/12158864953 for more details
We suggest you to escape special character (!) with the help of single or double quotes in the workflow for the exempt-issue-label value, that should reolve the issue. You can refer the workflow run with the suggested solution on the following url :- https://github.com/setup-actions-demo/stale-test/actions/runs/12199078047/job/34032166470
Please also refer to screen shot below for results."

**Comment by NotLazy** [comment] 2024-12-17 05:16
I think this fixed it, thank you.

**Comment by suyashgaonkar** [comment] 2024-12-18 07:51
Hi @NotLazy , Thank you for confirming and we will close this ticket, feel free to re-open this ticket incase of any queries or issue.

**Closed** 2024-12-18 07:52 UTC
Labels: bug
