### ISSUE TITLE
Unable to reserve cache with key _state

### ISSUE THREAD

**Issue by kamaradclimber** [actions/stale#1090] opened 2023-09-06 07:20 UTC
**Description:**

Processed issue cache cannot be saved, leading to going over same PRs over and over.

**Action version:**

b69b346013879cedbf50c69f572cd85439a41936

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  

Just wait for the action to launch

```
name: 'Stale issue handler'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

permissions:
  contents: read
  issues: read
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@b69b346013879cedbf50c69f572cd85439a41936
        id: stale
        with:
          stale-pr-message: 'This PR is stale because it has been open 30 days with no activity. Remove stale label (or add the `never-stale` label) otherwise this PR will be closed in 30 days'
          close-pr-message: 'This PR has been closed because it remained without activity for 30 days and in "stale" state for 30 days. Of course, you can reopen it if necessary.'
          days-before-stale: 30
          days-before-close: 30
          close-pr-label: 'closed-reason: stale'
          exempt-pr-labels: 'never-stale'
          exempt-draft-pr: true # warning: this consumes 1 additional API request per PR
          operations-per-run: 100 # let’s increase batch size if necessary
      - name: Print outputs
        run: echo ${{ join(steps.stale.outputs.*, ',') }}
```

**Expected behavior:**

Cache being used to go over all PR (1000+ in our repo).

**Actual behavior:**

Action go over the same 500PR.

In the action logs:
```
Github API rate remaining: 14887; reset at: Wed Sep 06 2023 06:27:06 GMT+0000 (Coordinated Universal Time)
state: persisting info about 459 issue(s)
/usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /home/runner/work/logs-backend/logs-backend --files-from manifest.txt --use-compress-program zstdmt
Failed to save: Unable to reserve cache with key _state, another job may be creating this cache. More details: Cache already exists. Scope: refs/heads/prod, Key: _state, Version: fa41d75081481069cfb6b92a5f83a94c6e06ef3ab2e6b762649ac5f86f46153f
```

Cache file `_state` does exist but has been created once and never updated apparently.

**Comment by dsame** [comment] 2023-09-06 08:45
Hello @kamaradclimber , i see the log message `another job may be creating this cache` - is it the real situation?
As a first attempt to solve the problem can you please remove the cache manually and confirm the problem raised once again despite no other jobs run stale action?

To remove the cache manually, please click `actions` tab, next `Caches` under `Management` title in sidebar and then `delete` button against the _state cache.

**Comment by kamaradclimber** [comment] 2023-09-06 08:56
Hello @dsame thanks for your reply.
I’m relatively confident no other job is trying to update/create this file since it was not present before I updated the action yesterday.
I already tried to delete the `_state` file once (yesterday when seing this for the first time) and have let the action create it again (run n+1) and then fail again (run n+2 and following).

**Comment by kamaradclimber** [comment] 2023-09-06 09:00
I got a bit further this time:

1. delete the cache file
2. launch manually action
```
The saved state was not found, the process starts from the first issue.
...
Github API rate used: 101
Github API rate remaining: 14731; reset at: Wed Sep 06 2023 09:04:45 GMT+0000 (Coordinated Universal Time)
state: persisting info about 452 issue(s)
/usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /home/runner/work/logs-backend/logs-backend --files-from manifest.txt --use-compress-program zstdmt
Cache Size: ~0 MB (1168 B)
Cache saved successfully
```
Now the cache file exist correctly
3. Relaunch the job a second time
```
The saved state was not found, the process starts from the first issue.
...
Github API rate used: 101
Github API rate remaining: 14628; reset at: Wed Sep 06 2023 09:04:45 GMT+0000 (Coordinated Universal Time)
state: persisting info about 452 issue(s)
/usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /home/runner/work/logs-backend/logs-backend --files-from manifest.txt --use-compress-program zstdmt
Failed to save: Unable to reserve cache with key _state, another job may be creating this cache. More details: Cache already exists. Scope: refs/heads/prod, Key: _state, Version: fa41d75081481069cfb6b92a5f83a94c6e06ef3ab2e6b762649ac5f86f46153f
```


so my understanding is that the method checking for cache existence is not working as expected because I would have assumed the cache to be found on the second run (and it did exist).

**Comment by jonstacks** [comment] 2023-09-08 01:05
I was recently hitting the same thing using the latest `main` and adding

```
permissions:
  actions: write
```

fixed it for me.

I'm not entirely sure, but what I think is happening is that [these calls](https://github.com/actions/stale/blob/b69b346013879cedbf50c69f572cd85439a41936/src/classes/state/state-cache-storage.ts#L33-L66) are using an octokit client with the `GITHUB_TOKEN` which I believe can vary based on user settings. However, the `@actions/cache` is using an [environment variable](https://github.com/actions/toolkit/blob/e26febd9886a792d9d30aa907f621157df0058e3/packages/cache/src/internal/cacheHttpClient.ts#L67-L76) for uploading and restoring the cache.

I think giving it `actions:write` also grants it more permissions than it probably needs, but it worked for me. I haven't looked too deep but I wonder if those other 2 octokit calls could use the `@actions/cache` client and get their permissions from the `ACTIONS_RUNTIME_TOKEN`.

**Comment by kamaradclimber** [comment] 2023-09-08 10:02
Indeed the workaround is correct:
```
state: persisting info about 609 issue(s)
/usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /home/runner/work/logs-backend/logs-backend --files-from manifest.txt --use-compress-program zstdmt
Cache Size: ~0 MB (1512 B)
Cache saved successfully
```
Thanks @jonstacks . I’ll keep the permission until there is a fix in the action.

**Comment by dsame** [comment] 2023-09-08 14:59
Hello @kamaradclimber , i suspect
```
permissions:
  contents: write
  issues: write
```

as it mentioned in the [README](https://github.com/actions/stale#recommended-permissions) could be enough since the action was tested with it.

Thank you @jonstacks for the note, but the `ACTIONS_RUNTIME_TOKEN` variable is not documented and should not be used. But the set of the required permission is given in the README, so they should be used first.

**Comment by kamaradclimber** [comment] 2023-09-08 15:06
Ok I’ll try with those options as well. Readme was unclear about the fact it might be required to have those write permissions for statefulness.

**Comment by jonstacks** [comment] 2023-09-09 05:56
@dsame, sorry for the confusion. I worded it poorly, but didn't mean to suggest that the `ACTIONS_RUNTIME_TOKEN` variable should be used directly since it is undocumented. I was thinking that instead of using an octokit client for checking the cache, the native `@actions/cache` library(which internally makes use of the `ACTIONS_RUNTIME_TOKEN` and is already used) could be the only method of interacting with the cache and just handle errors if restoring from a particular cache key fails instead of proactively using an octokit client with the `GITHUB_TOKEN` to check if it exists or not.

From the [github docs](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#how-the-permissions-are-calculated-for-a-workflow-job), 

> The permissions for the GITHUB_TOKEN are initially set to the default setting for the enterprise, organization, or repository. If the default is set to the restricted permissions at any of these levels then this will apply to the relevant repositories. For example, if you choose the restricted default at the organization level then all repositories in that organization will use the restricted permissions as the default. The permissions are then adjusted based on any configuration within the workflow file, first at the workflow level and then at the job level. Finally, if the workflow was triggered by a pull request from a forked repository, and the Send write tokens to workflows from pull requests setting is not selected, the permissions are adjusted to change any write permissions to read only

I think this means that the permissions for the GITHUB_TOKEN might work without adding `actions: write` in some organizations or repositories, but others will have issues if their organization policy is using restricted permissions.I think using only `@actions/cache` would bypass this issue.

**Comment by dsame** [comment] 2023-09-11 06:28
Hello @jonstacks , much thanks for the clarification. The problem is @action/cache uses undocumented limited API that is different from GitHub API and the using of 2 different clients is an known flaw caused by the limitation of the cache API and it is planned to be fixed. But, for now, to have `actions: write` or `context: write` is the only solution. 

Did this answer helps?

**Comment by dsame** [comment] 2023-10-18 06:51
@jonstacks i am closing the issue as resolved with workaround, but please feel free to reopen it or create new one if the problem still exists

**Closed by dsame** 2023-10-18 06:51 UTC
Labels: bug

**Comment by PlayLikeNeverB4** [comment] 2024-11-01 14:32
For people coming from google: I needed to add `actions: write`, but also https://github.com/actions/stale/issues/1136

**Comment by z3ntu** [comment] 2025-02-19 07:54
Is there a reason this is still not documented in the README? Would be as simple as adding one line to the example, no?

Additionally only the `actions` permission is documented at https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#permissions , `context` is not documented at all. What actual permissions does that grant?
