### ISSUE TITLE
'Label does not exist' error when removing issues from stale state

### ISSUE THREAD

**Issue by sampaiodiego** [actions/stale#173] opened 2020-09-17 21:18 UTC
Apparently starting from version v3.0.9 (based on the date it started to happen) I started to get the following error when the actions was removing the stale label of an issue:
```
##[error]Error removing a label: Label does not exist
```

This was the first run it happened: https://github.com/RocketChat/Rocket.Chat/runs/907729444?check_suite_focus=true#step:3:401

This is letting all issues still marked as stable, not sure it is also preventing them to be closed.

As [you can see](https://github.com/RocketChat/Rocket.Chat/actions/runs/181500400/workflow#L37) we use the `stat: stale` label, which is [still valid](https://github.com/RocketChat/Rocket.Chat/labels/stat%3A%20stale)

It took me a long time to notice this, as we have too many issues 🙈

**Comment by hross** [comment] 2020-09-18 09:38
This appears related to https://github.com/actions/stale/issues/98 (or at least might very well be, since your label has a space in it)

**Comment by sampaiodiego** [comment] 2020-09-21 12:18
thanks @hross .. any reason why it'd would until before July 24th and then stopped  working?

**Comment by jacekbogdanski** [comment] 2020-10-06 06:23
I'm getting the same error message for `status:stale` label, so it doesn't seem to be only related to space or also `:` character is causing the issue.

**Comment by ran-huang** [comment] 2020-11-05 06:04
I'm getting the same error message for `lifecycle/stale` label. It seems to be related to `/` as well.

**Comment by hross** [comment] 2020-11-20 12:00
https://github.com/actions/stale/pull/199 might resolve this issue. I am updating the latest tracking branch now. please let me know if this fixes your issue

**Comment by fatedier** [comment] 2020-11-22 08:13
@hross  It seems not fixed for `lifecycle/stale`.

Should I specify the tag `v3.0.14` instead of `v3`?

**Comment by C0ZEN** [comment] 2020-11-22 10:11
I find a reproduction of the error and I am working on a fix.

**Comment by C0ZEN** [comment] 2020-11-22 11:08
The fix I provided was not covering this case.

The issue here is related to the Octokit API when using the `removeLabel` method because the name of the label is formatted like this: `encodeURIComponent(label)`.
The tests are not covering this case.

A label like `stat: stale` will be encoded to `stat%3A%20stale`.
So basically I could remove the `encodeURIComponent` nevertheless if Octokit and GitHub actions are not able to parse it correctly either I do not see a case where labels containing special characters is viable.
The [octokit documentation](https://octokit.github.io/rest.js/v18#issues-remove-label) is not telling much about the format.
The [GitHub documentation](https://developer.github.com/v3/issues/labels/#remove-a-label-from-an-issue) neither.
@hross what do you think?
The worst case scenario IMO is that the remove label no longer works at all but it's easy to reverse since it's only one row change.

Anyway [this commit](https://github.com/actions/stale/pull/220/commits/5dd1e06c9b416192c333a7b6d2a376536eddb08a) fix the issue and it's included in [this PR](https://github.com/actions/stale/pull/220).

**Comment by fatedier** [comment] 2020-12-23 05:18
Any update on this issue?

**Comment by pantharshit00** [comment] 2021-01-01 21:43
I am also experiencing this with `status/needs-action` label. I would appreciate if fix is merged and released soon.

**Closed** 2021-01-15 11:51 UTC
