### ISSUE TITLE
New comments do not remove the Stale label

### ISSUE THREAD

**Issue by gergelyke** [actions/stale#21] opened 2019-09-13 14:58 UTC
As raised in https://github.com/uber-web/baseui/pull/1892, it seems like new comments do not remove the Stale label. Do we miss anything in our configuration?

```yml
name: 'Close stale issues'
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue is stale because it has been open 30 days with no activity. If it's still valid, please remove the stale label or comment on the issue, otherwise this ticket will be closed in 5 days"
          days-before-stale: 30
          days-before-close: 5
```

**Comment by LekoArts** [comment] 2019-09-27 20:09
I'd also be interested in knowing if this is a bug or user error.

**Comment by eileenmcnaughton** [comment] 2019-10-23 00:08
I am +1 on that feature being useful!

**Comment by MikeyMJCO** [comment] 2019-10-25 10:39
Also +1 on the feature being useful :-)

**Comment by LekoArts** [comment] 2019-10-29 15:10
@gergelyke @eileenmcnaughton @MikeyMJCO 
I've implemented this feature in our fork here: https://github.com/gatsbyjs/stale/blob/128ed907d5174a32717e7761e63294f5c747d8e2/src/main.ts#L122-L130

It lists all comments since the "days-before-stale" and filters for bot/user comments. If it can find user comments, the resulting array is not empty and hence the function return true.

**Comment by ruudk** [comment] 2019-11-08 17:00
@LekoArts so cool, did you consider proposing this as a PR to this repo? Would love this to be standard feature ❤️

**Comment by eileenmcnaughton** [comment] 2019-11-08 20:11
Agree - this needs to be a standard feature before the main feature is usable

**Comment by LekoArts** [comment] 2019-11-09 00:25
I changed the logic in the meantime to a more robust way of checking it: https://github.com/gatsbyjs/stale/blob/gatsby-refactoring/src/main.ts#L143

This is all WIP so use it at your own risk, we're still testing ourselves. And if they maintain the repository again and would accept a PR we gladly would PR that upstream.

**Comment by eileenmcnaughton** [comment] 2019-11-09 00:28
Hmm so the upstream repo is not maintained anymore :-(

**Comment by TheSalesOpsGuy** [comment] 2020-03-03 02:04
Were you ever able to merge your fork/updates into the main action? I'm trying to get the old probot functionality back as well (remove label if commented).

**Comment by LekoArts** [comment] 2020-03-03 09:14
You can use our fork if you want: https://github.com/gatsbyjs/stale
It's been working great for us. Since the repo still seems inactive a PR seems unfeasible - we'd be happy to send it in though.

**Comment by Tejas2805** [comment] 2020-03-20 22:28
Hi,

Any way to stop issues from closing?

**Comment by dev-zero** [comment] 2020-04-16 09:02
It would be nice if it could then also remove other labels as well. Our use case is that we would like to only have stale-handling for issues marked with `needinfo`. In case of a comment both `needinfo` and `stale` labels should be removed.

**Comment by hross** [comment] 2020-04-16 19:55
I agree this should be done. I'll add it to the list (I'm actively reviving this repo since it was somewhat stale a while ago).

**Comment by ramnes** [comment] 2020-04-19 19:07
Just discovering this and yeah, it's much needed, because if users are not able to stop the countdown, then as a maintainer I'd probably want the issue to be closed right away instead.

**Comment by TheSalesOpsGuy** [comment] 2020-04-20 18:46
> Just discovering this and yeah, it's much needed, because if users are not able to stop the countdown, then as a maintainer I'd probably want the issue to be closed right away instead.

I think the issue is just that the label isn't cleared, the script still checks for the last updated date on the issue so a user commenting resets the counter, it just doesn’t also clear the flag (which may or may not be a good thing depending on how you like your labels to work)

**Comment by hross** [comment] 2020-05-02 10:34
@damccorm PR is up over here (not quite working yet): https://github.com/actions/stale/pull/58 if you want to review it

**Comment by Gustry** [comment] 2020-05-13 07:24
FYI #58 has been merged. You can try again.

**Comment by MikeyMJCO** [comment] 2020-05-27 12:23
This is working for us now.

**Comment by Tejas2805** [comment] 2020-07-09 08:31
Still doesn't work for me. My configuration makes it runs every min, still.

![Screen Shot 2020-07-09 at 4 31 16 PM](https://user-images.githubusercontent.com/35946746/87016742-af4c7200-c201-11ea-8214-34c06c729968.png)

**Comment by MikeyMJCO** [comment] 2020-07-09 08:32
> Still doesn't work for me. My configuration makes it runs every min, still.
> 
> ![Screen Shot 2020-07-09 at 4 31 16 PM](https://user-images.githubusercontent.com/35946746/87016742-af4c7200-c201-11ea-8214-34c06c729968.png)

Can you link your repo?

**Comment by Tejas2805** [comment] 2020-07-09 08:34
> > Still doesn't work for me. My configuration makes it runs every min, still.
> > ![Screen Shot 2020-07-09 at 4 31 16 PM](https://user-images.githubusercontent.com/35946746/87016742-af4c7200-c201-11ea-8214-34c06c729968.png)
> 
> Can you link your repo?

https://github.com/Tejas2805/Github-Actions

**Comment by MikeyMJCO** [comment] 2020-07-09 08:36
Can you try adding `remove-stale-when-updated: 'True'` to your yml file.

**Comment by MikeyMJCO** [comment] 2020-07-09 08:43
You also have to factor in that it will only run on a limited number of issues/PR per run and so it may take a few runs to get to the changes.

**Comment by MikeyMJCO** [comment] 2020-07-09 08:44
Ah - nvm - found it. It's ignoring your comments.

**Comment by MikeyMJCO** [comment] 2020-07-09 08:45
`Comments not made by Tejas2805 or another bot: 0`

https://github.com/Tejas2805/Github-Actions/runs/853183570?check_suite_focus=true

**Comment by MikeyMJCO** [comment] 2020-07-09 08:45
Try with a comment made by someone else!

**Comment by Tejas2805** [comment] 2020-07-09 08:46
Any reason? Cause the PR is made by me.

**Comment by MikeyMJCO** [comment] 2020-07-09 08:47
Yeah - it ignores the author from what I can see!

**Comment by MikeyMJCO** [comment] 2020-07-09 08:49
I made a comment to test - if you can increase the frequency of your runs again!

**Comment by MikeyMJCO** [comment] 2020-07-09 08:50
And nevermind - it ran and remove the label!

**Comment by Tejas2805** [comment] 2020-07-09 08:51
Any way to make it remove when the author comments? Cause I think the "stale" part comes from the fact that the author is not active on it.

**Comment by MikeyMJCO** [comment] 2020-07-09 08:55
Okay so the answer is yes, it ignores `github.context.actor` which is the user who setup/runs the GitHub action. 

So it's not ignoring you because you're the author, it's ignoring you because you run the action!

**Comment by Tejas2805** [comment] 2020-07-09 08:57
> So it's not ignoring you because you're the author, it's ignoring you because you run the action!

Ah! Makes sense. Thank you for your help.

**Comment by MikeyMJCO** [comment] 2020-07-09 09:03
@hross I'm gonna suggest that you close this issue now if that seems appropriate? It's original issue has been addressed!

**Closed** 2020-07-09 18:28 UTC

**Comment by rdxmb** [comment] 2021-01-26 11:20
Does this problem still exist? See https://github.com/helm/helm/issues/4262#issuecomment-767414363

**Comment by bridgetkromhout** [comment] 2021-01-28 03:22
> Does this problem still exist? See helm/helm#4262 (comment)

@rdxmb The helm/helm repo stale issue action (https://github.com/helm/helm/actions?query=workflow%3A%22Close+stale+issues%22) runs once per day, not on-demand. So you'll see if you re-check that issue that you did indeed get the issue marked as not-stale - it just wasn't instant.
