### ISSUE TITLE
Action is not working and is always erroring out

### ISSUE THREAD

**Issue by faustroxas** [actions/stale#1154] opened 2024-04-16 06:57 UTC
**Description:**
Tried using the action and only got this error everytime. Created the a token with the right permissions as well
![image](https://github.com/actions/stale/assets/63102171/077ecb68-0b98-48fe-b69c-abd905a4270a)

Here is the code:

```jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v7
        with:
          stale-issue-label: "Stale"
          stale-pr-label: "Stale"
          days-before-stale: 60
          days-before-close: 7
          stale-issue-message: "This issue is stale because it has been open for 60 days with no activity."
          stale-pr-message: "This PR is stale because it has been open for 60 days with no activity."
          close-issue-message: "This issue was closed because it has been stale for 7 days since being marked as stale."
          close-pr-message: "This PR was closed because it has been inactive for 7 days since being marked as stale."
          repo-token: ${{ secrets.PR_ACCESS_TOKEN }}
```

**Action version:**
@v9

**Platform:**
- [x] macOS

**Runner type:**
- [x] Hosted

**Repro steps:**  
Copy the action step.

**Expected behavior:**
Closed old PRs and Issues 

**Actual behavior:**
Error: Not Found

**Comment by marlun78** [comment] 2024-08-12 06:57
I have the same issue, @faustroxas did you manage to solve it?

**Comment by faustroxas** [comment] 2024-08-12 06:58
> I have the same issue, @faustroxas did you manage to solve it?

Yeah. I used the github default token instead of ours. Seems like there are missing perms that are not stated

**Comment by suyashgaonkar** [comment] 2024-11-15 09:39
Hi @faustroxas , Thank you for confirming that the issue is resolved after changing token. We are closing the ticket, you can let us know if you still need any assistance on this.

**Closed** 2024-11-18 12:05 UTC
Labels: bug
