### ISSUE TITLE
Delete branch option does not appear to respect forks

### ISSUE THREAD

**Issue by MichaelJJ** [actions/stale#881] opened 2022-12-13 00:59 UTC
## Describe your issue

It appears that the delete branch option does not identify if the branch is from a fork and will attempt to delete a branch with the same name in the parent repository.

## Further context

As an example, if I fork a repository, the PR branch will be `my-fork:main`. If delete branch is true, then the stale action will attempt to delete branch `main` in the parent (primary) repo.

The stale action should check if the closed PR branch is a fork and either skip branch deletion, or attempt to delete the branch in the fork.

Looking at the code https://github.com/actions/stale/blob/main/src/classes/issues-processor.ts#L923 the action is simply taking `pullRequest.head.ref` which is simply the branch name and does not give an indication if this is a fork repo branch. The payload appears to have several ways to detect if this branch is from a fork, including `pullRequest.head.repo.fork: true` or checking `pullRequest.head.repo.owner`.

**Comment by IvanZosimov** [comment] 2022-12-21 08:33
Hi, @MichaelJJ 👋 Thanks for the bug report, we will take a look at it and get back to you with updates!

**Comment by dsame** [comment] 2023-01-23 19:58
Hello @MichaelJJ,

While trying to reproduce the problem it occurred to me i did not understand the issue well. 

`the branch is from a fork` according to the description literally means `a branch of the other repo used to create a PR`

So can the desired behaviour be said as "do not attempt to delete the branches for the staled PR"?

**Comment by MichaelJJ** [comment] 2023-01-23 20:11
I believe the simplest fix would be to check if the PR head is a fork repository, skip branch deletion for that PR even if the option is enabled.


Here is an example:

I fork a repo, and commit changes to a branch named "test-branch" on the Fork. I create a Pull Request from Fork branch "test" to the parent (original) repo.

The Pull Request becomes stale, and I have the delete branch option enabled. When the stale job runs, it closes the Pull Request in the parent (original) repo and then attempts to delete a branch named "test-branch" in Repo A, even though the PR branch originates from a fork.

If you look at the code here: https://github.com/actions/stale/blob/main/src/classes/issues-processor.ts#L923 it is simply looking for the PR branch name, and should also be checking if the PR originates from a fork. If my PR head is "ForkA:test-branch", the code `pullRequest.head.ref` will simply return `test-branch`, which may result in deleting a branch that should not be removed.

**Comment by dsame** [comment] 2023-01-24 00:47
@MichaelJJ , and here we are 
https://github.com/actions/stale/pull/913/files#diff-93e32a46e13f11c2066be36506b0f153d7da2b6b8d787da9177c10692ce50fc5R926

The idea is: delete the branch if
 - `pullRequest.head.repo === null` -- PR's branch is not forked 
 or
 - `pullRequest.head.repo.full_name === '${context.repo.owner}/${context.repo.repo}'`  - PR is from the same repo
 
 Do you think we are on the same page?

**Comment by MichaelJJ** [comment] 2023-01-24 01:21
I think that would cover it, the branch would only be deleted if the PR head is the repo, and not a fork. Thanks!

**Comment by dsame** [comment] 2023-01-26 08:03
@MichaelJJ  The related [PR](https://github.com/actions/stale/pull/913) merged and can be used immediately with

```
- uses: actions/stale@main
```

**Comment by dsame** [comment] 2023-02-02 07:14
Hello @MichaelJJ , i am closing the issue because the related PR has been merged, but please feel free to reopen it or create new one if the problem still exists.

**Closed by dsame** 2023-02-02 07:14 UTC
Labels: bug

**Comment by panticmilos** [comment] 2023-03-22 14:12
hi @MichaelJJ, we have released a new major [version](https://github.com/actions/stale/releases/tag/v8.0.0) of action, that is including a fix for this issue.

Could you confirm everything works as expected?
